import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  Award,
  Boxes,
  Building2,
  CheckCircle2,
  ClipboardList,
  Cloud,
  Compass,
  Cpu,
  Database,
  FileText,
  Flag,
  Gauge,
  GitBranch,
  Globe2,
  Handshake,
  Layers,
  LayoutGrid,
  Lightbulb,
  Lock,
  Map,
  Network,
  Package,
  Rocket,
  Settings2,
  Shield,
  Hexagon,
  Target,
  Timer,
  Users,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

/** Rotate distinct Lucide icons for card grids so pages aren't icon-monotone. */
const POOL: LucideIcon[] = [
  Hexagon,
  Layers,
  Shield,
  Cloud,
  Database,
  Network,
  GitBranch,
  Workflow,
  Rocket,
  Target,
  Gauge,
  Lock,
  Boxes,
  Cpu,
  Lightbulb,
  Compass,
  Package,
  Wrench,
  Users,
  Building2,
  Handshake,
  Globe2,
  Flag,
  Award,
  Activity,
  LayoutGrid,
  ClipboardList,
  FileText,
  Map,
  Settings2,
  Timer,
  Zap,
];

export function pickIcon(index: number): LucideIcon {
  return POOL[index % POOL.length]!;
}

export const ChallengeIcon = AlertTriangle;
export const OutcomeIcon = CheckCircle2;
export const MetricIcons: LucideIcon[] = [Timer, Target, Layers, Gauge, Flag, Award, Activity, Zap];
